### ISSUE TITLE
Override properties are not affecting the redis configuration: redis_password  & redis_logfile

### ISSUE THREAD

**Issue by stephansarver** [DavidWittman/ansible-redis#100]
When adding the following properties to the vars/main.yml and including the file in the main.yml that
i.e.
__________________________________   
vars_files:
   vars/main.yml
tasks\:
   include: tasks/master.yml
__________________________________  
and using the DavidWittman.redis role
i.e.
__________________________________  
 name: "Configure the master redis server."
  hosts: redis-master
  roles:
     DavidWittman.redis
  sudo: yes
__________________________________  
The following properties in vars/main.yml do not seem to have an effect on the redis configuration file:

__________________________________
redis_password: somePasswordThatYouWillNeverGUessBecauseItIsSoExcruciatinglyLong
redis_logfile: '/var/log/redis.log'
__________________________________  

Which look like the following after the Ansible run is compete.
__________________________________  
# requirepass foobared    
logfile ""
__________________________________  
  
Sorry the markdown is interfering with the code above but you should get the gist of it!

**Comment by DavidWittman** [comment]
@stephansarver can you provide the full playbook which you're using? Wrap it in triple backticks (\`\`\`playbook\`\`\`) for syntax highlighting.

Also, you should not be manually editing any variables within this role; they should all be set within your playbook.

**Comment by stephansarver** [comment]
OK so I don't know what is different butt it must be a PEBKAC issue. Since I blew away the original stuff I could not get working here is the test files that do work:

~~~main.yml~~~
`
`
`
---
- hosts: redis-master
  user: vagrant
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - DavidWittman.redis
# The following functionality seems to be missing to add this property change!
#  tasks:
    # Add the masterauth configuration so when this master fails and comes back up it can be turned into a slave automatically.
#    - lineinfile: dest=/etc/redis/6379.conf regexp="^# masterauth <master-password>" line="masterauth {{ master_auth_pass }}"
    # Restart the service after the configuration changes.
#    - service: name=redis_6379 state=restarted

`
`
`

~~~vars/main.yml~~~
`
`
`
---
#https://github.com/DavidWittman/ansible-redis
redis_version: 3.0.7
redis_password:  "{{ master_auth_pass }}"
redis_logfile: '/var/log/redis.log'
redis_sentinel_logfile: '/var/log/redis_sentinel.log'
redis_sentinel_monitors:
- name: "{{ master_name }}"
  host: "{{ master_addr }}"
  port: "{{ master_port }}"
  quorum: 2
  auth_pass: "{{ master_auth_pass }}"
  down_after_milliseconds: 30000
  parallel_syncs: 1
  failover_timeout: 180000
  notification_script: false
  client_reconfig_script: false

`
`
`

~~~inventorry~~~

`
`
`
[redis-master]
33.33.33.21 master_name=master1 master_addr=33.33.33.21 master_port=6379 master_auth_pass=somelongpassword

`
`
`

This issue should be closed!
