### ISSUE TITLE
Setting advanced values in configuration file

### ISSUE THREAD

**Issue by bencooling** [DavidWittman/ansible-redis#105]
I would like to set values in the redis.config under "Advanced" such as `hash-max-ziplist-entries`. 

Is there a preferred method for doing that?

Would a new role variable for a redis.config file to override the default tempting solution be an option?

Thanks,
Ben

**Comment by DavidWittman** [comment]
> Would a new role variable for a redis.config file to override the default tempting solution be an option?

Absolutely. I can add some of those more advanced values in, or you can submit a PR if you'd like.

I've considered adding a free-form value which allows the user to specify extra parameters which aren't yet templated, this sounds like a good reason to do that as well.

**Comment by bencooling** [comment]
Thanks. I will try and submit a PR soon! 
In the meantime if anyone is interested, my quick and dirty workaround involving ansible:

```
  tasks:
    - copy: src=./redis.conf dest=/etc/redis/6379.conf
    - service: name=redis_6379 state=restarted
```
