### ISSUE TITLE
Support for building a 32bit Redis

### ISSUE THREAD

**Issue by splitice** [DavidWittman/ansible-redis#108]
If the option `32bit` is given to make, redis builds a 32bit binary on a 64bit platform.

It would be useful if this could be a variable.

See http://redis.io/topics/memory-optimization for some of the reasons why this might be desirable.

**Comment by DavidWittman** [comment]
Good idea. I'll get this added in.

**Comment by DavidWittman** [comment]
@splitice Do you have any steps for successfully compiling with `make 32bit`? I'm getting some jemalloc errors even after installing `libc6-dev-i386`.

**Comment by splitice** [comment]
What errors?

I compiled redis on Debian Wheezy without issue. There some tips on the redis repository README, perhaps that helps?

**Comment by 3choBoomer** [comment]
@DavidWittman any update on this? Do you need any help?

**Comment by DavidWittman** [comment]
@3choBoomer I've been neglecting this one. Feel free to open a PR if you have the cycles.

**Comment by DavidWittman** [comment]
I started work on this in https://github.com/DavidWittman/ansible-redis/tree/108-make-32-bit.

**Comment by DavidWittman** [comment]
Closed by #141
