### ISSUE TITLE
Symlink redis to /usr/bin

### ISSUE THREAD

**Issue by izolate** [DavidWittman/ansible-redis#119]
As far as I can tell, both `redis-cli` and `redis-server` aren't symlinked to `/usr/bin` during install. Is there any reasoning behind this?

**Comment by DavidWittman** [comment]
@izolate Yes... this role was originally using the `alternatives` module to handle this, but was removed due to a regression discovered in https://github.com/DavidWittman/ansible-redis/issues/50.

I'm confident the issue has been addressed though and the alternatives should be brought back in.
