### ISSUE TITLE
Ansible didn't continue after enable service step

### ISSUE THREAD

**Issue by chaintng** [DavidWittman/ansible-redis#123]
This line https://github.com/DavidWittman/ansible-redis/blob/master/tasks/server.yml#L24
```
fatal: [104.199.185.189]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'redis_6379'\": "}
```

I have to manually SSH into the server and run below command
`systemctl enable redis_6379`

I use Debian Jessie on GCP

The playbook then stop again when i'm trying to deploy sentinel.

I already set `ansible_become=true` in the host file
i use ansible 2.2 on OSX.

Please advise

**Comment by bbaassssiiee** [comment]
Looks like Ansible 2.2 service: still has this problem https://github.com/ansible/ansible-modules-core/issues/915
