### ISSUE TITLE
Systemd service does not start

### ISSUE THREAD

**Issue by rfleschenberg** [DavidWittman/ansible-redis#130]
When the role tries to start the redis service, I get this error:

```
[/etc/systemd/system/redis_6379.service:10] Executable path is not absolute, ignoring: "/opt/redis/bin/redis-server" /etc/redis/6379.conf
systemd[1]: redis_6379.service lacks ExecStart setting. Refusing.
```

I think the problem is that we have some overquoting in `redis.service.j2`. I end up with this line in the output file `/etc/systemd/system/redis_NNNN.service`:

```
ExecStart="/opt/redis/bin/redis-server" /etc/redis/6379.conf
```

After manually modifying the file to look like this, I can start the service:
```
ExecStart=/opt/redis/bin/redis-server /etc/redis/6379.conf
```

**Comment by DavidWittman** [comment]
Thanks for reporting this @rfleschenberg. This should now be closed by #129.

**Comment by danielkza** [comment]
@rfleschenberg I actually meant for the quotes to stay, and they seemed to work fine on Ubuntu 14.04 and 16.04. The [systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines) says they are allowed. What version of systemd were you using?

**Comment by DavidWittman** [comment]
@chaintng reported the same issue on Debian 8. I didn't confirm but was able to confirm that these changes didn't have a negative effect on Ubuntu (save for the fact that it breaks when the redis dir contains a space).

**Comment by danielkza** [comment]
@DavidWittman I see. I don't think many people should be using paths with spaces, so it should be fine. Seems I was a bit overzealous with the quoting.

**Comment by rfleschenberg** [comment]
For the record: I was using Debian Jessie with systemd `215-17+deb8u4`. I guess Ubuntu is using a more recent version.

**Comment by danielkza** [comment]
@rfleschenberg My test with 14.04 should have gotten it though. Maybe it was flawed, since 14.04's systemd support is flaky at best.
