### ISSUE TITLE
/var/run/redis_2323 directory cannot be created in systemd service

### ISSUE THREAD

**Issue by DBLaci** [DavidWittman/ansible-redis#132]
Ubuntu 16.04 service not working by default.

Problem:

ExecStartPre=-/bin/mkdir /var/run/redis

Fails on service start (after reboot) because /run is tmpfs, and var/run/redis is removed on reboot. The error is:

    # systemctl restart redis_2323
    Job for redis_2323.service failed because the control process exited with error code. See "systemctl status redis_2323.service" and "journalctl -xe" for details.

    # journalctl -xe
    mkdir[1937]: /bin/mkdir: cannot create directory '/var/run/redis': Read-only file system
    chown[1940]: /bin/chown: cannot access '/var/run/redis': No such file or directory
    systemd[1]: redis_2323.service: Control process exited, code=exited status=1
    systemd[1]: Failed to start Advanced key-value store.
    -- Subject: Unit redis_2323.service has failed
    ...

For workaround, I set this in the variables:

    redis_pidfile: "/var/lib/redis/{{ redis_port }}.pid"

I tried this in the [Service]:
    PermissionsStartOnly=true

It did not helped.

**Comment by thbar** [comment]
I met the exact same issue, as well on Ubuntu 16.04. Thanks for the work-around, will try that out!

**Comment by DavidWittman** [comment]
From what I can tell, it looks like the right way to handle this is with tmpfiles.d: https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html. Thanks systemd!

**Comment by DavidWittman** [comment]
```
ubuntu@ubuntu-xenial:~$ cat /etc/tmpfiles.d/redis.conf 
d    /run/redis   0755 redis redis
```

This did the trick for me. I'll create a branch for some further testing.

**Comment by DavidWittman** [comment]
https://github.com/DavidWittman/ansible-redis/tree/132-systemd-tmpfiles seems to work in my testing. @thbar or @DBLaci let me know if you have any issues with this.

**Comment by thbar** [comment]
@DavidWittman I upgraded to 9937b2e5ec8c371f77f384b8252049e3344ffce7 this morning and did a bit of testing. Everything seems to run smoothly including at reboot time in my VM. Thanks for the fast patch!

& thanks again @DBLaci for initially reporting this, I was really wondering what was happening there.
