### ISSUE TITLE
Interactive authentication required

### ISSUE THREAD

**Issue by thbar** [DavidWittman/ansible-redis#137]
On initial setup, I get this error from times to times:

```
RUNNING HANDLER [DavidWittman.redis : restart redis {{ redis_port }}] **********
fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service redis_6379: Failed to restart redis_6379.service: Interactive authentication required.\nSee system logs and 'systemctl status redis_6379.service' for details.\n"}
```

I haven't fully understood what happens, but I do believe a likely fix is to use `become: yes` at the right place (for now I'll be fixing this by attempting to use become yes globally.

**Comment by DavidWittman** [comment]
@thbar What distribution is this running on? And are you running the role as `root` or another user with sudo access?

**Comment by thbar** [comment]
Quick reply from my phone : I'm on Ubuntu xenial, and using a sudoer
(deploy) not root.
Le sam. 17 déc. 2016 à 17:53, David Wittman <notifications@github.com> a
écrit :

**Comment by DavidWittman** [comment]
Thanks. I'll see if I can reproduce the issue.

**Comment by jimmy** [comment]
I ran into this issue as well. In my case, I was passing a `become_user` var to the role, but Ansible 2.2 has [a bug](https://github.com/ansible/ansible/issues/17490) where vars passed to roles are not honored in the role's handlers.

**Comment by pangolingo** [comment]
I experienced this same issue on Ubuntu 16.04, running Ansible 2.2.0.0. 
The handler "restart redis {{ redis_port }}" fails with the message shown above.
I re-ran the playbook and it worked the second time.

**Comment by DavidWittman** [comment]
Yeah, this is an Ansible bug. It should be upstream soon... if you're still having issues, try version 2.1.3.

**Comment by thbar** [comment]
Follow-up on this: I confirm that upgrading to Ansible 2.2.1.0 (up from 2.2.0.0) solves that issue. Thanks everyone, and H/T @jimmy for pointing to the Ansible bug reference.

**Comment by RubenGarcia** [comment]
I am using ansible 2.5.1 and I found the error appeared again:
- name: reboot database server
  service:
    name: postgresql
    enabled: yes
    state: restarted
  become: yes

fatal: [138.246.233.254]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "masked": null, 
            "name": "postgresql", 
            "no_block": false, 
            "state": "restarted", 
            "user": false
        }
    }, 
    "msg": "Unable to restart service postgresql: Failed to restart postgresql.service: Interactive authentication required.\nSee system logs and 'systemctl status postgresql.service' for details.\n"
}

**Comment by RubenGarcia** [comment]
Sorry, was trying to run this as postgres user which cannot become root.
