### ISSUE TITLE
Warnings on Redis 3.2.6 startup

### ISSUE THREAD

**Issue by thbar** [DavidWittman/ansible-redis#138]
When using redis 3.2.6, I get the following logs at startup:

> Dec 12 10:15:11 SERVER redis_6379[1041]: Redis 3.2.6 (00000000/0) 64 bit, standalone mode, port 6379, pid 1041 ready to start.
> Dec 12 10:15:11 SERVER redis_6379[1041]: WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> Dec 12 10:15:11 SERVER redis_6379[1041]: Server started, Redis version 3.2.6
> Dec 12 10:15:11 SERVER redis_6379[1041]: WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> Dec 12 10:15:11 SERVER redis_6379[1041]: The server is now ready to accept connections on port 6379

I have no idea if this occurs in earlier versions or not, but thought it was worth tracking.

On THP, I started investigating and found [this](https://github.com/antirez/redis/issues/3176).

**Comment by DavidWittman** [comment]
Thanks for reporting this. There's some more discussion on this issue in https://github.com/DavidWittman/ansible-redis/pull/103. I'm going to close this as a dupe.
