### ISSUE TITLE
Redis won't start on ubuntu 16.04

### ISSUE THREAD

**Issue by KopiasCsaba** [DavidWittman/ansible-redis#142]
Hi!

On an ubuntu 16.04 vm redis won't start, as the /var/run directory is readonly at the time the systemd service would like to start. (No idea why)

> Dec 22 15:14:50 kupacvirt mkdir[1139]: /bin/mkdir: cannot create directory '/var/run/redis': Read-only file system
Dec 22 15:14:50 kupacvirt chown[1149]: /bin/chown: cannot access '/var/run/redis': No such file or directory
Dec 22 15:14:50 kupacvirt systemd[1]: redis_6379.service: Control process exited, code=exited status=1
Dec 22 15:14:50 kupacvirt systemd[1]: Failed to start Advanced key-value store.
Dec 22 15:14:50 kupacvirt systemd[1]: redis_6379.service: Unit entered failed state.
Dec 22 15:14:50 kupacvirt systemd[1]: redis_6379.service: Failed with result 'exit-code'.

The init script can be fixed (not sure if it's the correct solution, but works) with the replacing of ExecStartPre-s ith RuntimeDirectory:
> #ExecStartPre=-/bin/mkdir /var/run/redis
#ExecStartPre=/bin/chown -R redis:redis /var/run/redis
RuntimeDirectory=redis

Please check it out! 

Thanks!

**Comment by DavidWittman** [comment]
@KopiasCsaba this should have been fixed by https://github.com/DavidWittman/ansible-redis/pull/135. Are you running the latest version of this role?
