### ISSUE TITLE
FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: daemon_reload"}

### ISSUE THREAD

**Issue by JimBarrows** [DavidWittman/ansible-redis#143]
ansible-playbook 2.1.1.0
It looks like the "daemon_reload" parameter has been moved to the  ([systemd module](https://docs.ansible.com/ansible/systemd_module.html) from the service module.  

I'm an ansible newbie, but if all that's needed is to change to the systemd module, than I can do it and send you a pull request if you like.

**Comment by DavidWittman** [comment]
AFAIK, the `service` module should be forwarding the parameters to the platform specific module, but I could be wrong. It looks like this behavior was fixed in Ansible 2.2.x, but I'll make some changes for the sake of compatibility.
