### ISSUE TITLE
host inverntory question

### ISSUE THREAD

**Issue by dimthe** [DavidWittman/ansible-redis#147]
Hello
this is from your readme

[redis-master]
redis-master.example.com

[redis-slave]
redis-slave0[1:3].example.com

[redis-sentinel]
redis-sentinel0[1:3].example.com redis_sentinel=True

can you please explain what does 1:3 stand for ? 
assuming you have 1 host for master , 1 for slave and 1 for sentinel
do i still need that 1:3 ?

**Comment by DavidWittman** [comment]
@dimthe That is just a pattern which matches `redis-slave01.example.com`, `redis-slave02.example.com`, and `redis-slave03.example.com`. See https://docs.ansible.com/ansible/intro_patterns.html for more details.
