### ISSUE TITLE
In redis.conf.j2 bug for redis 3.2.8

### ISSUE THREAD

**Issue by jiming** [DavidWittman/ansible-redis#156]
notify-keyspace-events {{ redis_notify_keyspace_events }}

will generalte 

_notify-keyspace-events_ 

not 

_notify-keyspace-events ""_

Without the empty string, redis 3.2.8 cannot startup

Thanks!

**Comment by DavidWittman** [comment]
Thanks @jiming! I'll get this fixed here shortly.
