### ISSUE TITLE
Standard command is not accepting 

### ISSUE THREAD

**Issue by ranjeetranjan** [DavidWittman/ansible-redis#163]
Hi Guys,

I am sorry to ask very small question I have to ask. 
I have installed successfully but when I am running some standard question its not accepting. 
>> redis-cli

Please help.

**Comment by DavidWittman** [comment]
redis-cli is available at `/opt/redis/bin/redis-cli`. Once #119 is closed (which I will be doing here shortly), it will be available at `/usr/bin/redis-cli` via alternatives.
