### ISSUE TITLE
Why check if redis user exists?

### ISSUE THREAD

**Issue by eRadical** [DavidWittman/ansible-redis#181]
What is the rationale behing checking for user existence?

https://github.com/DavidWittman/ansible-redis/blob/0b5887b3016e1b684da95cdba0d6c1d9f5ef4007/tasks/install.yml#L27-L47

The when clause from user creation should simply go away.

Instead of interpreting it as "make user redis if not exists" that should be read/seen as "make sure user redis exists"... more inclined to the state of things rather than action.

Same goes for the redis group which is now checked through the existence of the user.

[Would be glad to make a pull request on this but I wanted to see if there is any rationale that I missed.]

**Comment by DavidWittman** [comment]
I haven't looked at this in a while, but I think the logic here was to prevent changes to an already existing redis user. If you look at [the original commit](https://github.com/DavidWittman/ansible-redis/pull/144/commits/6631fce5293139f9796e359d276758351c5973df) there's mention of a failure when running usermod in that case.
