### ISSUE TITLE
Time for a 1.2.7 release?

### ISSUE THREAD

**Issue by pburkholder** [DavidWittman/ansible-redis#224]
Hi - I'm code reviewing a colleague's PR, and I hope that instead of pointing to a commit hash or fork, I could point to release number. Might you be able to cut a release soon? 

 Thanks, Peter

**Comment by DavidWittman** [comment]
Thanks for mentioning this @pburkholder. I just tagged 1.2.7.

**Comment by pburkholder** [comment]
![image](https://user-images.githubusercontent.com/1211146/64895296-1a610280-d64a-11e9-9aa3-4d1ec00a188b.png)
🎉 

🙇
