### ISSUE TITLE
Add Threaded I/O options to config

### ISSUE THREAD

**Issue by calvinbui** [DavidWittman/ansible-redis#242]
Redis 6 has some new options for multithreading. They can be seen at http://download.redis.io/redis-stable/redis.conf in the `Threaded I/O` section.

I can work on this but I was thinking to add the ability to add more configuration options. Something like:

vars:
```
redis_config_additional: |
  io-threads 4
  io-threads-do-reads yes
```

with the default option being `""`

jinja template:
```
...
{% if redis_config_additional|length %}
# Additional
{{ redis_config_additional }}
{% endif %}
...
```

This will allow users to add their own config without the role having to manually specify new ones all the time

**Comment by DavidWittman** [comment]
+1 this would resolve https://github.com/DavidWittman/ansible-redis/issues/105 too
