### ISSUE TITLE
Any plan for 1.2.8 release?

### ISSUE THREAD

**Issue by mjnaderi** [DavidWittman/ansible-redis#243]
Hi,

There are new commits and solved issues (e.g. #193) since v1.2.7. I install this role by running:

    ansible-galaxy install git+https://github.com/DavidWittman/ansible-redis,master
    mv ~/.ansible/roles/ansible-redis ~/.ansible/roles/davidwittman.redis

Is there any plan to release v1.2.8?

Thanks for the great job.

**Comment by DavidWittman** [comment]
Sure, I'll tag this now. Thanks for the nudge.
