### ISSUE TITLE
Installing redis from distribution repo

### ISSUE THREAD

**Issue by Yannik** [DavidWittman/ansible-redis#276]
Hi,

currently it is not supported to install redis from the main repository of a servers distribution. 

This may have been a good approach when redis was still in its infancy, but today you can get pretty mature versions of redis from these repos. It has the benefit of staying up-to-date with regards to security much easier than having to carefully watch changelogs/cves (and then install from source again).

Is this a deliberate design choice, or would you be open for a PR which supports installation from the distro repository?

If not, I'd be curious to learn why. :-)

Best regards
Yannik

**Comment by DavidWittman** [comment]
No reason other than your stated theory: it was good enough in its infancy, which is about when I made this role. And honestly -- as evidenced by the backlog of issues/PRs here -- I don't have time or a specific interest to change/test everything required to add the feature. I'd happily accept a PR implementing it, however.

**Comment by Yannik** [comment]
@DavidWittman 

Hey David, I took the time to create a PR as approved by you earlier. It would be great if you could have a look at it :-)

**Comment by DavidWittman** [comment]
> @DavidWittman
> 
> Hey David, I took the time to create a PR as approved by you earlier. It would be great if you could have a look at it :-)

Thank you for the nudge. My wife and I just had a baby this week, I'll try and take a look at this sometime over the next week or two.

**Comment by Yannik** [comment]
Thanks, David, and best of luck to your family!
