### ISSUE TITLE
Include deprecated 

### ISSUE THREAD

**Issue by zam-ali** [DavidWittman/ansible-redis#281]
Hello,
Can you please change all the include keywords in [tasks/main.yml](https://github.com/DavidWittman/ansible-redis/blob/56491474bc5b24e302a971c962263e84b091df89/tasks/main.yml) to "include_tasks" as the include keyword is deprecated and will be removed.
Thanks

**Comment by DavidWittman** [comment]
Fixed in #291

**Comment by p-rintz** [comment]
Will there be a new release that includes this fix?
Thank you!
