### ISSUE TITLE
Adding reids user fails if user already exists and has a process attached to it

### ISSUE THREAD

**Issue by rubenruizdegauna** [DavidWittman/ansible-redis#47]
Hi @DavidWittman ,

When installing sentinel after already have redis installed, it fails in the "add user" step as redis is currently running and the user is attached to it.

TASK: [ansible-redis | add redis user] ***************************************\* 
failed: [ruben-redis-sentinel] => {"failed": true, "name": "redis", "rc": 8}
msg: usermod: user redis is currently used by process 23205

FATAL: all hosts have already failed -- aborting

I guess a quick solution would be to check if the user already exists.

```
 name: check if redis user exists
  shell: id {{ redis_user }} 2> /dev/null | wc -l
  register: redis_user_exists

- name: add redis user
  user:
    name={{ redis_user }}
    comment="Redis"
    home={{ redis_install_dir }}
    shell=/bin/false
    system=yes
  when: redis_user_exists.stdout == "0"
```

Cheers and thanks for the role.

**Comment by blelump** [comment]
I've encountered the same issue while applying this role on VM with existing Redis instance. The output of `add redis user` is:
```
failed: [syllabus1] => {"failed": true, "name": "redis", "rc": 8}
msg: usermod: user redis is currently used by process 15309


FATAL: all hosts have already failed -- aborting
```

Env:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

$ cat /etc/passwd | grep redis                                                           
redis:x:117:126:redis server,,,:/var/lib/redis:/bin/false
```

If Redis was previously installed with system package manager (eg. apt), the default user `$HOME` is `/var/lib/redis` whereas with this role it has `/opt/redis`. Changing the `redis_install_dir` to `/var/lib/redis` seems to solve this issue.
