### ISSUE TITLE
redis_daemonize: no, no --> causes false

### ISSUE THREAD

**Issue by klemenkobetic** [DavidWittman/ansible-redis#68]
when parameter
redis_daemonize: no

it causes
daemonize False

available values are yes or no ;
>>> 'daemonize False'
argument must be 'yes' or 'no'

**Comment by DavidWittman** [comment]
@klemenkobetic this has to do with the fact that Ansible treats yes/no values as booleans. The correct way to set this value is as a string. E.g.

``` yaml
redis_daemonize: "no"
```

I'll update the documentation to reflect this.

**Comment by klemenkobetic** [comment]
Yes, forgot about that!

Thanks for the clarification and update in the doc!
