### ISSUE TITLE
Default collation and char set

### ISSUE THREAD

**Issue by markalanevans** [DavidWittman/ansible-redis#72]
Do you have a way to set the default collation and character set like this role:

https://github.com/ANXS/mysql

```
- name: foobar
    collation: "utf8_general_ci"        # optional, defaults to "utf8_general_ci"
    encoding: "utf8"                    # optional, defaults to "utf8"
```

**Comment by DavidWittman** [comment]
As far as I can tell, Redis stores binary data and doesn't seem to care about collation or encoding. Here's [a similar issue](https://github.com/antirez/redis/issues/567) filed against Redis itself, which was closed. I'm going to do the same with this issue, but if there's a particular problem I can help solve, I can re-open it.
