### ISSUE TITLE
add redis user task fails if /opt folder doesn't exist

### ISSUE THREAD

**Issue by callmeed** [DavidWittman/ansible-redis#74]
The home dir for `add redis user` is {{ redis_install_dir }}, which by default is /opt/redis. However, this fails for me if the /opt dir doesn't already exist. 

This was on an Ubutu 14.04 VPS.

**Comment by DavidWittman** [comment]
Thanks for reporting this issue @callmeed. It's a little strange to me that the /opt directory isn't present, but I guess on a tiny VPS that might be expected. I'll move this task so that it occurs after the install dir is created.

**Comment by callmeed** [comment]
Thanks and keep up the great work
