### ISSUE TITLE
/var/run/redis/redis.pid --> init file needs to create /var/run/redis

### ISSUE THREAD

**Issue by klemenkobetic** [DavidWittman/ansible-redis#75]
since /var/run is not permanent (well, subfolders and files) i added to init script

DAEMON=/opt/redis/bin/redis-server
PIDFOLDER=/var/run/redis
PIDFILE=${PIDFOLDER}/${REDIS_PORT}.pid

REDIS_USER=redis
CONF="/etc/redis/${REDIS_PORT}.conf"
CLIEXEC=/opt/redis/bin/redis-cli

mkdir ${PIDFOLDER}
chown $REDIS_USER:root ${PIDFOLDER}

if [ -r /etc/default/redis_${REDIS_PORT} ]; then
    . /etc/default/redis_${REDIS_PORT}
fi

**Comment by DavidWittman** [comment]
Hey @klemenkobetic... Thanks for reporting this. This is a dupe of #59. It's been stale for a while now though. I'll see if I can't get that addressed there myself sometime soon.
