### ISSUE TITLE
How to deploy multi redis

### ISSUE THREAD

**Issue by raingolee** [DavidWittman/ansible-redis#78]
hi:

If i want to deploy 32 instances redis, and i have to write 32 times "redis_port"

how can i combine that such as 
redis_port: 2000-2031

**Comment by DavidWittman** [comment]
Hey @raingolee... I can't think of a clean way to accomplish this, nor have I seen any other roles which implement this pattern. You'll need to explicitly identify the port on which the redis instance is intended to run.

I'm going to close this for now, but if you have any ideas around how to implement feel free to comment.

**Comment by raingolee** [comment]
Hi, David. okay, just close it.. if there is a clean way that i would pull
a request.. thanks

2015-09-20 7:19 GMT+08:00 David Wittman <notifications@github.com>:

**Comment by 3choBoomer** [comment]
@raingolee Can you give an example of how you are currently configuring multiple instances to a single machine?

**Comment by DavidWittman** [comment]
@3choBoomer see my comment [here](https://github.com/DavidWittman/ansible-redis/pull/71#issuecomment-132038482) for an example. Let me know if you have any issues!
