### ISSUE TITLE
Supporting HA Master with Slaves

### ISSUE THREAD

**Issue by adamstrawson** [DavidWittman/ansible-redis#94]
Not an issue, but more of a call for assistance!

Is there a way with ansible-redis (I assume using Sentenial) to have a High Availability setup for Master, and with multiple slaves connecting to the active master.

So for example;

            +--------+       +--------+
            -   M1   -  <=>  -   S1   -
            +--------+       +--------+
          _ _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
         /                  \                  \         
    +--------+          +--------+         +--------+
    -   C1   -          -   C2   -         -   C3   - 
    +--------+          +--------+         +--------+

S1 is a slave of M1, if M1 were to fail, S1 would be promoted to Master.

C1, C2, C3 are all slaves of M1 or S1 (depending which is the active master)

Thanks,
Adam

**Comment by DavidWittman** [comment]
Hey @adamstrawson. Did you get anywhere with this? I haven't tested this specific architecture, but it should be possible. I'll have to give it some thought and I can try to put together an example playbook for you.

**Comment by DavidWittman** [comment]
@adamstrawson This is more of a limitation of Redis than of this role, but it doesn't appear possible (within reason) to always have your dedicated slaves pointed to the _active_ master.

You can set `redis_slave_priority: 0` on each of the client nodes to prevent them from becoming master, but I just don't see a way to always point them to the current master without some sort of wizardry outside of what Redis provides. If you know of something I don't, let me know and I can accommodate that use case in this role.
